spring:
  application:
    name: "scheduler-service"

management:
  server:
    port: 8081

  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true
      show-details: never