spring:
  config:
    import: optional:file:./backend/.env.backend.local[.properties]

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:PT15M}

    internal-api:
      scheduler-api-key: ${SCHEDULER_API_KEY:local-scheduler-api-key}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


  app:
    kafka:
      topics:
        email-sending-tasks: EMAIL_SENDING_TASKS